const aiMessageElement = document.getElementById("ai-message");

const aiMessages = [
  "This page was generated by AI 🤖",
  "Powered by Artificial Intelligence 💡",
  "An AI model crafted this website 🌐",
  "Welcome to the future of web design, by AI 🚀",
];

function changeAiMessage() {
  const randomIndex = Math.floor(Math.random() * aiMessages.length);
  aiMessageElement.innerHTML = aiMessages[randomIndex];
}

changeAiMessage();
setInterval(changeAiMessage, 3000);
